### ISSUE TITLE
publicising local-persist && other volume drivers

### ISSUE THREAD

**Issue by briceburg** [CWSpear/local-persist#17]
@CWSpear  I learned of local-persist through your docker issue and posted about my use case there: https://github.com/docker/docker/issues/19990#issuecomment-188448278

It would be incredibly helpful to have a resource for finding docker volume plugins/drivers like these. Do you think it makes sense to add this to  https://github.com/docker/docker/blob/master/docs/extend/plugins.md  -- or is there a better spot?

Many thanks for your work!

**Comment by CWSpear** [comment]
That would probably be the best spot I can think of visibility-wise. But do you think it's "worthy?" Haha, I feel a little self-conscious adding it there myself. Maybe you could do it ;-)

One other thought is there are resources like https://github.com/veggiemonk/awesome-docker that may be worth adding this plugin to.

And I saw your comment on the Docker repo. Thank you for the kind words! I didn't want to respond on there with just a "thanks," since they have a bunch of people subscribed on there, so I'm glad you posted here.

**Comment by thaJeztah** [comment]
Feel free to open a pull-request for adding it to the `plugins.md` overview!

FYI, we want to make it easier to find (and install) plugins; there's a "roadmap" issue created for this here; https://github.com/docker/docker/issues/20363

**Comment by CWSpear** [comment]
See https://github.com/docker/docker/pull/20687/files. I don't know how I feel about the description, but at least it's there.

**Comment by CWSpear** [comment]
PR to add it to awesome docker: https://github.com/veggiemonk/awesome-docker/pull/154

**Comment by CWSpear** [comment]
I even tweeted (https://twitter.com/CWSpear/status/702900870048911362) and posted to Reddit (https://www.reddit.com/r/docker/comments/47jure/docker_create_volume_using_any_mountpoint_you/).

And with that... that's pretty much all the marketing I know, so unless you have any other ideas, I'm gonna close to puppy.
