### ISSUE TITLE
Using on Mac with latest docker for mac

### ISSUE THREAD

**Issue by indicalabs** [CWSpear/local-persist#41]
If we use this with swarm and AWS ebs volumes, should this be installed on the ec2?
Any way to use with Mac?
thanks.

**Comment by CWSpear** [comment]
I am not 100% sure on the swarm use case. The answer is: it depends.

As for Mac, you _can_ run it via its own container (see the README). There was a bug in how Docker for Mac mapped a folder it needed. I know it was fixed in Beta (I use the Beta channel) and I'm pretty sure it is fixed in release, too.
